### ISSUE TITLE
使用 for(auto& p: mp) 时 p 不是一个 const pair 吧

### ISSUE THREAD

**Issue by SamZhangQingChuan** [zqy1018/my_leetcode#2]
https://github.com/zqy1018/my_leetcode/blob/master/summaries/technique_STL.md

**Comment by zqy1018** [comment]
确实，p 应该只有键才是 const，值不是。感谢指出。
![image](https://user-images.githubusercontent.com/30336342/81503038-0b833a80-9314-11ea-9f49-a73a61692849.png)
